import numpy
from typing import Sequence, Tuple

def brute_sort_objects(data) -> Tuple[numpy.ndarray, numpy.ndarray]: ...
def brute_sort_objects_no_hash(data) -> Tuple[numpy.ndarray, numpy.ndarray]: ...
def direct_object_array(array: Sequence) -> numpy.ndarray: ...
