[build-system]
requires = [
    "setuptools >= 42",
    "wheel",
    "versioneer",
    "pybind11[global] == 2.13.6",
    "Amulet_pybind11_extensions @ git+https://github.com/Amulet-Team/Amulet-pybind11-extensions.git@f781177e52f352ea0c1750e9219a1a84f4ddd92f",
    "amulet_nbt == 4.0a12",
    "amulet_leveldb == 2.0a3",
]
build-backend = "setuptools.build_meta"

[project]
name = "amulet-core"
authors = [
    {name = "James Clare"},
    {name = "Ben Gothard"},
]
description = "A Python library for reading/writing Minecraft's various save formats."
dynamic = ["version", "readme"]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy ~= 2.0",
    "portalocker ~= 2.4",
    "platformdirs ~= 3.1",
    "pillow ~= 10.0",
    "amulet_runtime_final ~= 1.1",
    "amulet_compiler_target == 1.0",
    "amulet_nbt == 4.0a12",
    "amulet_leveldb ~= 2.0a3",
]

[project.optional-dependencies]
docs = [
    "Sphinx>=1.7.4",
    "sphinx-autodoc-typehints>=1.3.0",
    "sphinx_rtd_theme>=0.3.1",
]
dev = [
    "black>=22.3",
    "pre_commit>=1.11.1",
    "isort",
    "autoflake",
    "mypy",
    "types-pyinstaller",
    "wheel",
    "versioneer",
    "pybind11_stubgen" # @ git+https://github.com/Amulet-Team/pybind11-stubgen.git@c3a6ef67ec23d5a39e8cdc73b2c3cd8c1794d6f2",
]

[project.urls]
Homepage = "https://www.amuletmc.com"
Repository = "https://github.com/Amulet-Team/Amulet-Core"
Issues = "https://github.com/Amulet-Team/Amulet-Core/issues"

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
"*" = [
    "*Config.cmake",
    "**/*.png",
    "**/*.hpp",
    "**/*.dll",
    "**/*.so",
    "**/*.dylib",
    "**/*.lib",
]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[project.entry-points.pyinstaller40]
hook-dirs = "amulet.__pyinstaller:get_hook_dirs"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "src/amulet/_version.py"
versionfile_build = "amulet/_version.py"
tag_prefix = ""
parentdir_prefix = "amulet-"
