from _typeshed import Incomplete

class ChunkVersionComponent:
    __min_chunk_version: Incomplete
    __max_chunk_version: Incomplete
    __chunk_version: Incomplete
    def __init__(self, min_chunk_version: int, max_chunk_version: int, chunk_version) -> None: ...
    @property
    def min_chunk_version(self) -> int: ...
    @property
    def max_chunk_version(self) -> int: ...
    @property
    def chunk_version(self) -> int: ...
    @chunk_version.setter
    def chunk_version(self, chunk_version: int): ...
