class FinalisedStateComponent:
    __finalised_state: int
    def __init__(self) -> None: ...
    @property
    def finalised_state(self) -> int: ...
    @finalised_state.setter
    def finalised_state(self, finalised_state: int): ...
