from __future__ import annotations

import collections.abc
import typing

import amulet.level.java.anvil.region
import amulet_nbt

__all__ = ["AnvilDimension", "AnvilDimensionLayer", "RawChunkType"]

class AnvilDimension:
    def __init__(
        self,
        directory: str,
        layer_names: collections.abc.Iterable[str],
        mcc: bool = False,
    ) -> None: ...
    def all_chunk_coords(self) -> typing.Iterator[tuple[int, int]]: ...
    def compact(self) -> None: ...
    def delete_chunk(self, cx: int, cz: int) -> None: ...
    def get_chunk_data(self, cx: int, cz: int) -> dict[str, amulet_nbt.NamedTag]: ...
    def get_layer(self, layer_name: str) -> AnvilDimensionLayer: ...
    def has_chunk(self, cx: int, cz: int) -> bool: ...
    def has_layer(self, layer_name: str) -> bool: ...
    def set_chunk_data(
        self,
        cx: int,
        cz: int,
        data_layers: collections.abc.Iterable[tuple[str, amulet_nbt.NamedTag]],
    ) -> None: ...

class AnvilDimensionLayer:
    def __init__(self, directory: str, mcc: bool = False) -> None: ...
    def all_region_coords(self) -> typing.Iterator[tuple[int, int]]: ...
    def compact(self) -> None: ...
    def delete_chunk(self, cx: int, cz: int) -> None: ...
    def get_chunk_data(self, cx: int, cz: int) -> amulet_nbt.NamedTag: ...
    def get_region(
        self, rx: int, rz: int, create: bool = False
    ) -> amulet.level.java.anvil.region.AnvilRegion: ...
    def has_chunk(self, cx: int, cz: int) -> bool: ...
    def has_region(self, rx: int, rz: int) -> bool: ...
    def set_chunk_data(self, cx: int, cz: int, tag: amulet_nbt.NamedTag) -> None: ...

RawChunkType: typing.TypeAlias = dict[str, amulet_nbt.NamedTag]
