from __future__ import annotations

import typing

import amulet_nbt

__all__ = ["AnvilRegion", "RegionDoesNotExist"]

class AnvilRegion:
    class FileCloser:
        pass

    @typing.overload
    def __init__(
        self, directory: str, file_name: str, rx: int, rz: int, mcc: bool = False
    ) -> None: ...
    @typing.overload
    def __init__(self, directory: str, rx: int, rz: int, mcc: bool = False) -> None: ...
    @typing.overload
    def __init__(self, path: str, mcc: bool = False) -> None: ...
    def close(self) -> None: ...
    def compact(self) -> None: ...
    def contains(self, cx: int, cz: int) -> bool: ...
    def delete_batch(self, coords: list[tuple[int, int]]) -> None: ...
    def delete_value(self, cx: int, cz: int) -> None: ...
    def destroy(self) -> None: ...
    def get_coords(self) -> list[tuple[int, int]]: ...
    def get_file_closer(self) -> AnvilRegion.FileCloser: ...
    def get_value(self, cx: int, cz: int) -> amulet_nbt.NamedTag: ...
    def has_value(self, cx: int, cz: int) -> bool: ...
    def set_value(self, cx: int, cz: int, tag: amulet_nbt.NamedTag) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def rx(self) -> int: ...
    @property
    def rz(self) -> int: ...

class RegionDoesNotExist(RuntimeError):
    pass
