from __future__ import annotations

import amulet.level.abc.dimension
import amulet.version

__all__ = ["Level", "LevelMetadata"]

class Level(LevelMetadata):
    def close(self) -> None: ...
    def dimension_ids(self) -> list[str]: ...
    def get_dimension(
        self, dimension_id: str
    ) -> amulet.level.abc.dimension.Dimension: ...
    def open(self) -> None: ...
    def purge(self) -> None: ...
    def save(self) -> None: ...

class LevelMetadata:
    def is_open(self) -> bool: ...
    @property
    def level_name(self) -> str: ...
    @property
    def max_game_version(self) -> amulet.version.VersionNumber: ...
    @property
    def modified_time(self) -> float: ...
    @property
    def platform(self) -> str: ...
    @property
    def sub_chunk_size(self) -> int: ...
