from __future__ import annotations

import typing

import amulet.biome
import amulet.block
import amulet.level.java.chunk
import amulet.selection.box
import amulet.utils.lock
import amulet_nbt

__all__ = ["JavaRawDimension"]

class JavaRawDimension:
    def compact(self) -> None: ...
    def decode_chunk(
        self, raw_chunk: dict[str, amulet_nbt.NamedTag], cx: int, cz: int
    ) -> amulet.level.java.chunk.JavaChunk: ...
    def delete_chunk(self, cx: int, cz: int) -> None: ...
    def encode_chunk(
        self, chunk: amulet.level.java.chunk.JavaChunk, cx: int, cz: int
    ) -> dict[str, amulet_nbt.NamedTag]: ...
    def get_raw_chunk(self, cx: int, cz: int) -> dict[str, amulet_nbt.NamedTag]: ...
    def has_chunk(self, cx: int, cz: int) -> bool: ...
    def set_raw_chunk(
        self, cx: int, cz: int, chunk: dict[str, amulet_nbt.NamedTag]
    ) -> None: ...
    @property
    def all_chunk_coords(self) -> typing.Iterator[tuple[int, int]]: ...
    @property
    def bounds(self) -> amulet.selection.box.SelectionBox: ...
    @property
    def default_biome(self) -> amulet.biome.Biome: ...
    @property
    def default_block(self) -> amulet.block.BlockStack: ...
    @property
    def dimension_id(self) -> str: ...
    @property
    def lock(self) -> amulet.utils.lock.OrderedLock: ...
    @property
    def relative_path(self) -> str: ...
