from __future__ import annotations

import datetime

import amulet.level.abc.registry
import amulet.level.java.raw_dimension
import amulet.utils.lock
import amulet.version
import amulet_nbt

__all__ = ["JavaCreateArgsV1", "JavaRawLevel"]

class JavaCreateArgsV1:
    def __init__(
        self,
        overwrite: bool,
        path: str,
        version: amulet.version.VersionNumber,
        level_name: str,
    ) -> None: ...
    @property
    def level_name(self) -> str: ...
    @property
    def overwrite(self) -> bool: ...
    @property
    def path(self) -> str: ...
    @property
    def version(self) -> amulet.version.VersionNumber: ...

class JavaRawLevel:
    level_dat: amulet_nbt.NamedTag
    level_name: str
    @staticmethod
    def create(args: JavaCreateArgsV1) -> JavaRawLevel: ...
    @staticmethod
    def load(path: str) -> JavaRawLevel: ...
    def close(self) -> None: ...
    def compact(self) -> None: ...
    def get_biome_id_override(self) -> amulet.level.abc.registry.IdRegistry: ...
    def get_block_id_override(self) -> amulet.level.abc.registry.IdRegistry: ...
    def get_dimension(
        self, dimension_id: str
    ) -> amulet.level.java.raw_dimension.JavaRawDimension: ...
    def is_open(self) -> bool: ...
    def lock(self) -> amulet.utils.lock.OrderedLock: ...
    def open(self) -> None: ...
    def reload_metadata(self) -> None: ...
    @property
    def data_version(self) -> amulet.version.VersionNumber: ...
    @data_version.setter
    def data_version(self) -> None: ...
    @property
    def dimension_ids(self) -> list[str]: ...
    @property
    def modified_time(self) -> datetime.datetime: ...
    @property
    def path(self) -> str: ...
    @property
    def platform(self) -> str: ...
