from amulet.utils.lock import SharedLock, OrderedLock

def throw_deadlock() -> None: ...
def lock_shared_mutex(lock: SharedLock, count: int) -> None: ...
def lock_ordered_mutex(lock: OrderedLock, count: int) -> None: ...
