from typing import Any, Generator, TypeVar

from _typeshed import Incomplete
from amulet.resource_pack import BedrockResourcePack as BedrockResourcePack

T = TypeVar("T")
log: Incomplete

def generator_unpacker(gen: Generator[Any, Any, T]) -> T: ...
def get_latest() -> BedrockResourcePack: ...
def get_latest_iter() -> Generator[float, None, BedrockResourcePack]: ...
def get_bedrock_vanilla_fix() -> BedrockResourcePack: ...
def get_bedrock_vanilla_latest() -> BedrockResourcePack: ...
def get_bedrock_vanilla_latest_iter() -> (
    Generator[float, None, BedrockResourcePack]
): ...
