from __future__ import annotations

import amulet.chunk

__all__ = ["ChunkHandle"]

class ChunkHandle:
    def delete_chunk(self) -> None: ...
    def exists(self) -> bool: ...
    def get_chunk(self) -> amulet.chunk.Chunk: ...
    def set_chunk(self, chunk: amulet.chunk.Chunk) -> None: ...
    @property
    def cx(self) -> int: ...
    @property
    def cz(self) -> int: ...
    @property
    def dimension_id(self) -> str: ...
