from __future__ import annotations

import typing

import amulet.utils.signal

__all__ = ["AbstractProgressManager", "ProgressManager", "VoidProgressManager"]

class AbstractProgressManager:
    def get_child(
        self, progress_min: float, progress_max: float
    ) -> AbstractProgressManager: ...
    def register_progress_callback(
        self, callback: typing.Callable[[float], None]
    ) -> amulet.utils.signal.SignalToken[float]: ...
    def register_progress_text_callback(
        self, callback: typing.Callable[[str], None]
    ) -> amulet.utils.signal.SignalToken[str]: ...
    def unregister_progress_callback(
        self, token: amulet.utils.signal.SignalToken[float]
    ) -> None: ...
    def unregister_progress_text_callback(
        self, token: amulet.utils.signal.SignalToken[str]
    ) -> None: ...
    def update_progress(self, progress: float) -> None: ...
    def update_progress_text(self, text: str) -> None: ...

class ProgressManager(AbstractProgressManager):
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class VoidProgressManager(AbstractProgressManager):
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
