name: Unittests

on:
  push:
    branches:
      - master
      - main
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025-vs2026, python-version: '3.14', architecture: x64, whl: 'cp314-win_amd64' }
          - { os: windows-11-vs2026-arm, python-version: '3.14', architecture: arm64, whl: 'cp314-win_arm64' }
          - { os: macos-15-intel, python-version: '3.14', architecture: x64, whl: 'cp314-macosx_x86_64' }
          - { os: macos-15, python-version: '3.14', architecture: arm64, whl: 'cp314-macosx_arm64' }
          - { os: ubuntu-24.04, python-version: '3.14', architecture: x64, whl: 'cp314-manylinux_x86_64' }

    runs-on: ${{ matrix.cfg.os }}
    timeout-minutes: 45
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Build and Test
      run: |
        pip install cibuildwheel~=4.1
        cibuildwheel --only ${{ matrix.cfg.whl }} --output-dir dist .

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        path: dist/*
