name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025, python-version: '3.14', architecture: x64 }
          - { os: windows-11-arm, python-version: '3.14', architecture: arm64 }
          - { os: macos-15, python-version: '3.14', architecture: arm64 }

    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install build twine

    - name: Build
      run: |
        python -m build .

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_CORE_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing

    - name: Build Docs
      shell: bash
      env:
        RTDTOKEN: ${{ secrets.RTDTOKEN }}
        RTDURL: ${{ secrets.RTDURL }}
        TAGNAME: ${{ github.event.release.tag_name }}
      run: |
        release_regex_version='^([0-9]+\.[0-9]+(\.[0-9]+)?\.)([0-9]+)$'
        if [[ $TAGNAME =~ $release_regex_version ]]; then
          # if it is a full release trigger the stable docs build
          curl -X POST -d "branches=stable" -d "token=$RTDTOKEN" $RTDURL
        else
          # if it is a beta release trigger the beta docs build
          curl -X POST -d "branches=latest" -d "token=$RTDTOKEN" $RTDURL
        fi
