# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12' ]
        os: [ macos-15, windows-2025 ]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install build twine

    - name: Build
      run: |
        python -m build .

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_CORE_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing

    - name: Build Docs
      shell: bash
      env:
        RTDTOKEN: ${{ secrets.RTDTOKEN }}
        RTDURL: ${{ secrets.RTDURL }}
        TAGNAME: ${{ github.event.release.tag_name }}
      run: |
        release_regex_version='^([0-9]+\.[0-9]+(\.[0-9]+)?\.)([0-9]+)$'
        if [[ $TAGNAME =~ $release_regex_version ]]; then
          # if it is a full release trigger the stable docs build
          curl -X POST -d "branches=stable" -d "token=$RTDTOKEN" $RTDURL
        else
          # if it is a beta release trigger the beta docs build
          curl -X POST -d "branches=latest" -d "token=$RTDTOKEN" $RTDURL
        fi
