name: Unittests

on:
  push:
    branches:
      - master
      - main
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025, python-version: '3.14', architecture: x64 }
          - { os: windows-11-arm, python-version: '3.14', architecture: arm64 }
          - { os: macos-15-intel, python-version: '3.14', architecture: x64 }
          - { os: macos-15, python-version: '3.14', architecture: arm64 }
          - { os: ubuntu-24.04, python-version: '3.14', architecture: x64 }

    runs-on: ${{ matrix.cfg.os }}
    timeout-minutes: 45
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}
        
    - name: Build
      run: |
        pip install -v .[dev]
        python tools/compile_tests.py
        
    - name: Test with unittest
      run: python -m unittest discover -v -s tests
